// src/pages/reports/BuildingRentRoll.tsx
// Building Rent Roll / Tenant Report — a complete per-building tenant list
// with month-based rent collection, print and landscape PDF export.
// Read-only: nothing here modifies data.

import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { PageHeader } from "@/components/PageHeader";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ReportPrintBlock } from "@/components/reports/ReportPrintBlock";
import { useData } from "@/context/DataContext";
import {
  buildRentRoll,
  rentRollColumns,
  rentRollRowStrings,
  rentRollSummary,
  totalsOfRows,
  monthLabelOf,
  type RentRollRow,
  type RentRollTotals,
} from "@/lib/rentRoll";
import { downloadReportPdf } from "@/lib/reportPdf";
import { openReportPrintWindow } from "@/lib/reportPrint";
import { Building2, CalendarDays, Download, FileDown, Layers, Printer, Receipt, Search, TriangleAlert, Wallet, X } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";

const selectClass =
  "h-10 rounded-md border border-input bg-background px-3 text-sm text-foreground";

const emptyTotals: RentRollTotals = {
  totalUnits: 0,
  occupiedUnits: 0,
  vacantUnits: 0,
  totalRent: 0,
  totalCollected: 0,
  totalOutstanding: 0,
};

export default function BuildingRentRoll() {
  const [searchParams] = useSearchParams();
  const { buildings, units, leases, tenants, invoices, payments } = useData();
  const [buildingId, setBuildingId] = useState(searchParams.get("building") ?? buildings[0]?.id ?? "");
  const [monthYm, setMonthYm] = useState(() => new Date().toISOString().slice(0, 7));
  const [statusFilter, setStatusFilter] = useState("All");
  const [occupancyFilter, setOccupancyFilter] = useState("All");
  const [tenantSearch, setTenantSearch] = useState("");
  const [unitSearch, setUnitSearch] = useState("");

  const building = buildings.find((b) => b.id === buildingId) ?? buildings[0];

  // Complete roll for the building — ALL units, vacant included.
  const roll = useMemo(
    () =>
      building
        ? buildRentRoll({ building, units, leases, tenants, invoices, payments, monthYm })
        : { rows: [] as RentRollRow[], totals: emptyTotals },
    [building, units, leases, tenants, invoices, payments, monthYm],
  );

  const filteredRows = useMemo(() => {
    const tq = tenantSearch.trim().toLowerCase();
    const uq = unitSearch.trim().toLowerCase();
    return roll.rows.filter((r) => {
      const matchesStatus = statusFilter === "All" || r.status === statusFilter;
      const matchesOccupancy =
        occupancyFilter === "All" || (occupancyFilter === "Occupied" ? r.occupied : !r.occupied);
      const matchesTenant =
        !tq || r.tenantName.toLowerCase().includes(tq) || r.contact.toLowerCase().includes(tq);
      const matchesUnit = !uq || r.unit.toLowerCase().includes(uq);
      return matchesStatus && matchesOccupancy && matchesTenant && matchesUnit;
    });
  }, [roll, statusFilter, occupancyFilter, tenantSearch, unitSearch]);

  const hasFilters =
    statusFilter !== "All" ||
    occupancyFilter !== "All" ||
    tenantSearch.trim() !== "" ||
    unitSearch.trim() !== "";

  const clearFilters = () => {
    setStatusFilter("All");
    setOccupancyFilter("All");
    setTenantSearch("");
    setUnitSearch("");
  };

  const buildingNumber = building?.buildingNumber || building?.code || "";
  const title = building
    ? `BUILDING ${buildingNumber} ${building.name}`.toUpperCase()
    : "BUILDING RENT ROLL";
  const monthLabel = monthLabelOf(monthYm);
  const subtitle = `Rent Roll / Tenant Report · Month: ${monthLabel}`;
  const fileMonth = format(new Date(`${monthYm}-01T00:00:00`), "MMMM_yyyy");
  const fileBase = building
    ? `Building_${buildingNumber}_${building.name.replace(/\s+/g, "_")}_Rent_Roll_${fileMonth}`
    : `Rent_Roll_${fileMonth}`;

  const totalsOf = (rows: RentRollRow[]) => (rows.length === roll.rows.length ? roll.totals : totalsOfRows(rows));

  const sectionsFor = (rows: RentRollRow[]) => [
    { columns: rentRollColumns, rows: rentRollRowStrings(rows) },
    { heading: "Building Summary", info: rentRollSummary(totalsOf(rows)) },
  ];

  const handlePrint = (rows: RentRollRow[]) => {
    const ok = openReportPrintWindow({ title, subtitle, sections: sectionsFor(rows), orientation: "landscape" });
    if (!ok) {
      // Fall back to the in-page print stylesheet (report area only).
      window.print();
    }
  };

  const handleDownloadPdf = (rows: RentRollRow[], fileName: string) => {
    downloadReportPdf(
      {
        title,
        subtitle,
        orientation: "landscape",
        sections: sectionsFor(rows),
        footerNote: "Generated by Al Namlaiti Property Management System",
      },
      fileName.endsWith(".pdf") ? fileName : `${fileName}.pdf`,
    );
    toast.success(`${fileName}.pdf downloaded`);
  };

  const handleExportAllBuildings = () => {
    let count = 0;
    for (const b of buildings) {
      const r = buildRentRoll({ building: b, units, leases, tenants, invoices, payments, monthYm });
      if (r.rows.length === 0) continue;
      const num = b.buildingNumber || b.code || b.id;
      downloadReportPdf(
        {
          title: `BUILDING ${num} ${b.name}`.toUpperCase(),
          subtitle,
          orientation: "landscape",
          sections: [
            { columns: rentRollColumns, rows: rentRollRowStrings(r.rows) },
            { heading: "Building Summary", info: rentRollSummary(r.totals) },
          ],
          footerNote: "Generated by Al Namlaiti Property Management System",
        },
        `Building_${num}_${b.name.replace(/\s+/g, "_")}_Rent_Roll_${fileMonth}.pdf`,
      );
      count += 1;
    }
    if (count === 0) toast.info("No buildings with units to export.");
    else toast.success(`${count} building rent roll PDF(s) generated — check your downloads.`);
  };

  const filteredTotals = totalsOf(filteredRows);

  const summaryCards = [
    { label: "Total Units", value: String(filteredTotals.totalUnits), icon: Layers, tone: "bg-indigo-100 text-indigo-600" },
    { label: "Occupied Units", value: String(filteredTotals.occupiedUnits), icon: Building2, tone: "bg-emerald-100 text-emerald-600" },
    { label: "Vacant Units", value: String(filteredTotals.vacantUnits), icon: TriangleAlert, tone: "bg-slate-100 text-slate-600" },
    { label: "Monthly Rent", value: `BHD ${filteredTotals.totalRent.toFixed(3)}`, icon: Wallet, tone: "bg-blue-100 text-blue-600" },
    { label: "Rent Collected", value: `BHD ${filteredTotals.totalCollected.toFixed(3)}`, icon: Receipt, tone: "bg-emerald-100 text-emerald-600" },
    { label: "Outstanding", value: `BHD ${filteredTotals.totalOutstanding.toFixed(3)}`, icon: TriangleAlert, tone: "bg-orange-100 text-orange-600" },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Building Rent Roll" subtitle="Complete tenant list and rent collection per building" />

      {/* Actions */}
      <div className="flex flex-wrap items-center gap-2 print:hidden">
        <Button onClick={() => handleDownloadPdf(filteredRows, fileBase)}>
          <FileDown className="mr-2 h-4 w-4" /> Generate PDF
        </Button>
        <Button variant="outline" onClick={() => handlePrint(filteredRows)}>
          <Printer className="mr-2 h-4 w-4" /> Print
        </Button>
        <Button variant="secondary" onClick={() => handleDownloadPdf(roll.rows, fileBase)}>
          <Download className="mr-2 h-4 w-4" /> Export All
        </Button>
        <Button variant="secondary" onClick={handleExportAllBuildings}>
          <Download className="mr-2 h-4 w-4" /> Export All Buildings
        </Button>
        <span className="ml-auto text-sm text-muted-foreground">
          Showing {filteredRows.length} of {roll.rows.length} unit(s)
        </span>
      </div>

      {/* Filters */}
      <Card className="print:hidden">
        <CardContent className="flex flex-col gap-3 p-4">
          <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
            <select value={building?.id ?? ""} onChange={(e) => setBuildingId(e.target.value)} className={selectClass}>
              {buildings.map((b) => (
                <option key={b.id} value={b.id}>
                  {b.buildingNumber || b.code} — {b.name}
                </option>
              ))}
            </select>
            <div className="flex items-center gap-2">
              <CalendarDays className="h-4 w-4 text-muted-foreground" />
              <Input
                type="month"
                value={monthYm}
                onChange={(e) => setMonthYm(e.target.value)}
                className="w-40"
                aria-label="Rent month"
              />
              <Button variant="outline" size="sm" onClick={() => setMonthYm(new Date().toISOString().slice(0, 7))}>
                Current Month
              </Button>
            </div>
            <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className={selectClass}>
              <option value="All">All Lease Statuses</option>
              <option value="Active">Active</option>
              <option value="Expired">Expired</option>
              <option value="Terminating">Terminating</option>
              <option value="Draft">Draft</option>
              <option value="Vacant">Vacant</option>
            </select>
            <select value={occupancyFilter} onChange={(e) => setOccupancyFilter(e.target.value)} className={selectClass}>
              <option value="All">Occupied & Vacant</option>
              <option value="Occupied">Occupied</option>
              <option value="Vacant">Vacant</option>
            </select>
          </div>
          <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Search tenant or contact number..."
                value={tenantSearch}
                onChange={(e) => setTenantSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Search unit number..."
                value={unitSearch}
                onChange={(e) => setUnitSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Button variant="ghost" onClick={clearFilters} disabled={!hasFilters} className="lg:ml-auto">
              <X className="mr-2 h-4 w-4" /> Clear Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Summary */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6 print:hidden">
        {summaryCards.map((c) => (
          <Card key={c.label}>
            <CardContent className="p-4">
              <div className="flex items-center justify-between gap-2">
                <div>
                  <p className="text-xs font-medium text-muted-foreground">{c.label}</p>
                  <p className="mt-1 text-lg font-bold text-foreground">{c.value}</p>
                </div>
                <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${c.tone}`}>
                  <c.icon className="h-4 w-4" />
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* On-screen rent roll — the complete filtered list (no pagination) */}
      <Card className="print:hidden">
        <CardContent className="overflow-x-auto p-0">
          <table className="w-full text-sm">
            <thead className="bg-muted/50 text-muted-foreground">
              <tr>
                {rentRollColumns.map((c) => (
                  <th
                    key={c.label}
                    className={`px-3 py-3 font-medium ${c.align === "right" ? "text-right" : "text-left"}`}
                  >
                    {c.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {filteredRows.length === 0 ? (
                <tr>
                  <td colSpan={rentRollColumns.length} className="px-4 py-12 text-center text-muted-foreground">
                    No units match the current filters.
                  </td>
                </tr>
              ) : (
                filteredRows.map((r) => (
                  <tr key={`${r.unit}-${r.srNo}`} className={`hover:bg-muted/30 ${r.occupied ? "" : "bg-slate-50/60"}`}>
                    <td className="px-3 py-2.5 text-muted-foreground">{r.srNo}</td>
                    <td className={`px-3 py-2.5 font-medium ${r.occupied ? "" : "text-muted-foreground"}`}>{r.tenantName}</td>
                    <td className="px-3 py-2.5">{r.spec}</td>
                    <td className="px-3 py-2.5">{r.contact || "—"}</td>
                    <td className="px-3 py-2.5">{r.unit}</td>
                    <td className="px-3 py-2.5 text-right">{r.rent}</td>
                    <td className="px-3 py-2.5 text-right">{r.collected}</td>
                    <td className="px-3 py-2.5">{r.month}</td>
                    <td className="px-3 py-2.5 text-right">{r.outstanding}</td>
                    <td className="px-3 py-2.5">{r.leasePeriod}</td>
                    <td className="px-3 py-2.5">{r.remarks || "—"}</td>
                    <td className="px-3 py-2.5">{r.status}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </CardContent>
      </Card>

      {/* Print / PDF fallback version of the filtered report (in-page print stylesheet) */}
      <div className="hidden print:block">
        <ReportPrintBlock title={title} subtitle={subtitle} sections={sectionsFor(filteredRows)} />
      </div>
    </div>
  );
}
